services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # Puerto de la API S3
      - "9001:9001"   # Puerto de la consola web
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data: